networks:
  write-network:
  read-network:

#Database containers
services:
  rabbitmq:
    container_name: rabbitmq-management
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=Thierry
      - RABBITMQ_DEFAULT_PASS=Test1234=
  mssql-read:
    container_name: mssql-read
    build: ./MsSqlRead
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Test1234=
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
    ports:
      - 11433:1433
    networks:
      - read-network
    depends_on:
      - rabbitmq

  mssql-write:
    container_name: mssql-write
    build: ./MsSqlWrite
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Test1234=
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
    ports:
      - 21433:1433
    networks:
      - write-network
    depends_on:
      - rabbitmq

#Api Containers
  read-api:
    container_name: read-api
    build: ./ReadApi
    ports:
      - 18080:8080
    volumes:
      - shared:/app/shared
    networks:
      - read-network
    depends_on:
      - mssql-read

  write-api:
    container_name: write-api
    build: ./WriteApi
    volumes:
      - shared:/app/shared
    networks:
      - write-network
    ports:
      - 28080:8080
    depends_on:
      - mssql-write

volumes:
  shared: