networks:
  write-network:
  read-network:

#Database containers
services:
  # mysql:
  #   container_name: mysql-server
  #   image: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=Test1234+
  #     - MYSQL_DATABASE=my_test_db
  #     - MYSQL_USER=Thierry
  #     - MYSQL_PASSWORD=Test1234=
  #   networks:
  #     - read-network

  # mssql:
  #   container_name: mssql-server
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - MSSQL_SA_PASSWORD=Test1234=
  #     - MSSQL_PID=Developer
  #     - MSSQL_TCP_PORT=1433
  #     - MSSQL_LCID=1036   #French
  #   networks:
  #     - write-network

#Api Containers
  write-api:
    container_name: write-api
    build: ./WriteApi
    volumes:
      - shared:/shared
    networks:
      - write-network
  
  read-api:
    container_name: read-api
    build: ./ReadApi
    volumes:
      - shared:/shared
    networks:
      - read-network

volumes:
  shared: